[package]
name = "nexmark-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "nexmark"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["experimental-inspect", "extension-module", "abi3-py311"] }
nexmark = "0.2.0"
